# Generated by Django 5.2.15 on 2026-06-22 01:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.documents.models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("internships", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[("CV", "CV"), ("CONVENTION", "Convention"), ("REPORT", "Report")],
                default="CV",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                upload_to="documents/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf", "doc", "docx"]),
                    apps.documents.models.validate_document_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="internship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="internships.internship",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type", "status"], name="documents_d_documen_80b3b1_idx"
            ),
        ),
    ]
